### PR TITLE
feat: navigate from "Your Children" to specific tabs

### PR DESCRIPTION
**Pull request by PalmN72**
https://github.com/kolplattformen/skolplattformen/assets/98584401/d06714f8-ac23-4ec1-8d10-b7226614b445
#483

### CODE REVIEW

**Comment by PalmN72** [comment]
Found a bug, title doesn't change. Working on it!

**Comment by irony** [comment]
Really cool stuff! Looks amazing. Thank you! Will merge.

**Review by irony — APPROVED** [review]
Looks good

**Comment by irony** [comment]
Thanks a lot!

**Pull request merged**
