### PR TITLE
chore(build): fix github actions

### PR DESCRIPTION
**Pull request by believer**
This PR should fixes the `lerna bootstrap` step in GitHub actions. The problem was that `app` was using `yarn` while the other packages are using `npm`. This PR makes it consistent by using `yarn` for **all** packages. I've also added `.nvmrc`'s to app and API.

The default test in `app` was removed because it wasn't really being "used". I also fixed the test in `site` that was broken in #41.

### CODE REVIEW

**Comment by irony** [comment]
@JohanObrink - is this in conflict with the decision to make yarn as default for all RN packages?

**Comment by JohanObrink** [comment]
@irony Yes
@believer We actually decided to go the other direction and use `yarn` everywhere. Is this a decision you agree with?

**Comment by believer** [comment]
@JohanObrink sounds good to me! should we do that in this PR?

**Comment by JohanObrink** [comment]
@believer It might be best. We've had some instances of RN becoming sad because of dependency b0rks so itäs probably safest to keep the yarn.lock for the apps and nuke the package-lock files.

**Comment by believer** [comment]
Perfect, I'll make it happen

**Comment by believer** [comment]
@JohanObrink now we're using Yarn for all packages

**Review by JohanObrink — APPROVED** [review]
❤️

**Pull request merged**
